### ISSUE TITLE
Feature Request: Create a view that is "list" instead of "map"

### ISSUE THREAD

**Issue by momack2** [pln-planning-tools/Starmap#120]
In roadmaps like the FVM roadmap (fvm.filecoin.io) it is useful to see a single webpage where you can view the linear milestones top to bottom (including the description in prose). 

- It would be useful for multiple groups and to be rendered in a tool (vs manually created on websites)
- It would also be useful to be able to embed that in a website - so that it updates programmatically when the github issues are changed. 

![CleanShot 2022-11-16 at 19 20 02](https://user-images.githubusercontent.com/618519/202346732-5f927d93-f326-45fc-84b0-02c43c04e12b.png)

**Comment by juliaxbow** [comment]
Including some rough mockups below for how this could look. Let me know which direction is preferred and we can go from there. 

Some addt'l questions:
- How closely do we want this to match FVM formatting? The alternative is to include in table format
    - I assume we would like all parameters to be the same for this view, e.g. include explicit ETA rather than high-level month/quarter? This makes the FVM-style a bit less neat but shouldn't be a problem
- Is there any other metadata from GitHub we would like to include? 

Alt. 1 High Level List
![List View Alt 1 (FVM Style)](https://user-images.githubusercontent.com/58958327/210414698-fb3c8ca7-e5e2-449a-8ac2-5b6302abac85.png)

Alt. 2 Table View
![List View Alt 2 (Table)](https://user-images.githubusercontent.com/58958327/210414703-ca13c2b4-b262-452e-8494-f3dab3690507.png)

**Comment by SgtPooki** [comment]
ping @momack2 

I say we go with the first option for now.. it makes the descriptions much easier to read, and as our only view with descriptions, that's important.

cc @tinytb

**Comment by momack2** [comment]
I also like option 1 better!

**Comment by momack2** [comment]
I also think working on the list view is a more impactful short term win. we can debug specific css positioning changes after landing this.

**Comment by AlexxNica** [comment]
We may have to handle multiple items under the same date. Any ideas on how we would display that?

An idea using the FVM example as inspiration would be to show them under an indented list (like Milestone 2.1 there) and have the date be the header.

**Comment by SgtPooki** [comment]
> An idea using the FVM example as inspiration would be to show them under an indented list (like Milestone 2.1 there) and have the date be the header.

@AlexxNica I like that approach, we can fine-tune as we get feedback, but that sounds more than reasonable for now. Are you working on the list view? You mentioned, via slack, having put some effort toward that. I'm planning to take that on as core work tomorrow and finish within a week or so. lmk

**Comment by AlexxNica** [comment]
@SgtPooki I started exploring. I'll add that to a branch in my fork and ping you; hopefully that saves you some time. I can also help review the PR when it comes in. Sounds good?

**Comment by SgtPooki** [comment]
thanks Alex!

**Comment by AlexxNica** [comment]
Here's the template: https://codepen.io/AlexxNica/pen/gOdwxwa

I think the template can be a starting point (that's how I prototyped the list view before), but there are definitely other ways to achieve the same, so feel free to choose whatever method you're most comfortable with!

@SgtPooki let me know if it'd be helpful to pair up for some time next week to do this together. 🙌

**Comment by SgtPooki** [comment]
Thanks Alexx, that's a great snippet for showing the nesting :+1: 

got the basic view done for now. working on styling the titles and such before I hop into nesting:

![image](https://user-images.githubusercontent.com/1173416/221958750-da4fb61c-9a9d-4085-8aa8-01c3f2b5f417.png)

just using a simple grid and template areas for the items at this point

```jsx
      templateAreas={`"date icon title"
                      "empty line description"`}
      gridTemplateRows={'1fr 1fr'}
      gridTemplateColumns={'1fr 0.5fr 8fr'}
```

**Comment by SgtPooki** [comment]
I believe the intention with this list view was to render all children, but I don't think that's a great UX, and so the first pass is going to only render the direct children (similar to how overview only shows direct children). This causes a few issues with navigation within the list view.

The initial design doesn't give guidance on communicating to users what links are clickable or not, nor whether to differentiate between linkable children or not, so i've been looking over a number of separate ways to communicate this (because all issue titles are currently Blue and look clickable).

## Display all links as blue, clickable or not (in original mockup from Julia)

### Pros
* Looks great
* Hover state can potentially communicate clickability to users.

### Cons
* Cannot tell at first glance which items are clickable or not 

### Screenshot

![image](https://user-images.githubusercontent.com/1173416/222862029-fd78a5f6-c762-44e7-8f64-1fc04e7a74a2.png)

## Display clickable links as blue, and non-clickable as black. 

It's how we do it on overview/detailed view

### Pros
* Convention aligns with other screens
* Users can immediately see which items are clickable

### Cons
* Doesn't look great on list view.

### Screenshot

![image](https://user-images.githubusercontent.com/1173416/222860829-3737c20d-9626-4d9f-8b42-418a20c99adf.png)

## Use underlines

Very common and accessible; but not "pretty." Out of fashion.

### Pros
* Users can immediately see which items are clickable

### Cons
* We don't use underlines for links on starmap.site unconventional and surprising(UX bug)
* Doesn't look great

### Screenshot

![image](https://user-images.githubusercontent.com/1173416/222860768-8f5751e4-c5a8-48fe-bb93-420032b19044.png)


## Use an icon to indicate traversibility

### Pros
* Users can immediately see which items are clickable
* Looks good and gives flexibility with coloring
* link icon should be pretty intuitive in this scenario.

### Cons
* Can look odd depending on how we want to position it

### Screenshots

#### Arrow
![image](https://user-images.githubusercontent.com/1173416/222863269-f707f698-adda-472d-bbf5-e46e5ddbadb8.png)

### Link Icon (front)
![image](https://user-images.githubusercontent.com/1173416/222863827-46d6b74e-d9f4-4919-a3c7-6aff81a512b4.png)

### Link icon (rear)

![image](https://user-images.githubusercontent.com/1173416/222863866-89df7d7e-746e-4151-8856-b74704f3b9b6.png)


----

I'm going to go with the link icon in the front for now, but let me know if others have better ideas, comments, questions, or concerns.

cc @whizzzkid

**Comment by SgtPooki** [comment]
There is also a discussion in https://github.com/pln-planning-tools/Starmap/issues/196#issuecomment-1454171406 pertaining to parsing of "description:" content from milestones.
