### ISSUE TITLE
Multi-team roadmaps are useless

### ISSUE THREAD

**Issue by jsoares** [pln-planning-tools/Starmap#233]
Apologies for the clickbaity title, but here's what I mean:

![image](https://user-images.githubusercontent.com/547492/205131790-e23b647f-71e7-4576-b072-9ddb4434b4eb.png)

This stems from the fact that "themes" are also required to have ETAs and their children are not visible at the higher level. These ETAs are arbitrary, as these are standing subteams or work streams, yet they cause the underlying projects/milestones to get hidden from the macro view; in other words, a team roadmap that is structured as suggested provides _no_ useful information in the upper layer.

There isn't a clear solution to this, but the issue is twofold:
1. There is no support for rendering explicitly dateless running themes
2. The suggested format in the instructions is suboptimal in this model

It'd be great to handle themes (issues with no dates but with children) differently -- by passing them through as subsections in the higher-level roadmap. Alternatively, for a no-code solution, we could just adjust guidance to teams and drop themes in favour of listing all projects (projects, unlike themes, have actual end dates) as children of their root issue. I'm sure there are other solutions too, but the current one is just not it.

**Comment by SgtPooki** [comment]
> This stems from the fact that "themes" are also required to have ETAs 
This is a bug. We shouldn't be requiring ETAs on themes

> Alternatively, for a no-code solution, we could just adjust guidance to teams and drop themes in favour of listing all projects (projects, unlike themes, have actual end dates) as children of their root issue

based on the EngRes allhands today, I definitely agree that we need to do this. If we do, "themes" (i.e. parents) not having ETAs is no longer a bug, because projects should have ETAs.

I personally think we should lean into labels for configuring how StarMaps handles issues:
* "starmaps" label only: require children, ETA & description optional
* "starmaps-theme" label: require children, ETA & description optional
* "starmaps-deliverable" label: require ETA, children & description optional

"starmaps-theme" could easily be "starmaps-group" or other.

The tradeoffs are like so:
1. Current state: Overloaded handling of github issues (all issues are parsed the same) - unintuitive tool 
2. Proposed state: Specific handling of github issues via label - onboarding speedbumps

We currently only have 4 pieces of explicit metadata that help with determining how to render an issue:
1. is it the currently viewed root node
1. ETA
2. children issues
3. currently selected view mode

We can build some implicit metadata based on that:
1. is it a child (milestone item in overview)
   * It should have an ETA
   * It may have children
3. Is it a grandchild (milestone item in detailed view)  
   * It should have an ETA
   * It may have children
4. is it a root issue (currently viewed issue)
   * It must have children
   * it's ETA should be ignored
5. What is the ETA date-range of children of root issues (and child nodes on detailed view)?
   * We must check all children for ETA, but roadmaps can consist of roadmaps.. so to get this date-range, we should assume all children have ETAs, but we currently have no way of knowing if they actually should

And all of those rules (not an exclusive list) change when you change which root node you're viewing. 

With our current state, we have implicit UX patterns with which the tool needs to determine the correct parsing. 

With my proposed state, the onboarding would be slightly more burdensome, but it provides more metadata that would allow our tool to handle a GitHub issue expectedly.

**Comment by jsoares** [comment]
I like that direction!

**Comment by SgtPooki** [comment]
just an update here that we recently removed the requirement for a "starmaps" label, and I believe we're going to stay away from the requirement of labels altogether. I'm open to other solutions (markdown text to configure UI treatment) but am unsure where to take this. Deferring this for now.

cc @tinytb @momack2
